### ISSUE TITLE
unable to deploy quantum-chemistry-iiith Lab using ads in local environment (vagrant)

### ISSUE THREAD

**Issue by fireballpoint1** [vlead/ovpl#94]
During the deployment of lab caught following error
```
[E 180629 09:24:55 controller:83] test_lab(); Test failed with error:Test lab failed
[I 180629 09:24:55 web:1946] 200 POST / (::1) 224449.65ms
192.168.33.1 - - [29/Jun/2018 09:24:55] "POST / HTTP/1.1" 200 -
192.168.33.1 - - [29/Jun/2018 09:24:55] "GET /static/css/main.css HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Werkzeug-0.12.2-py2.6.egg/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.6/site-packages/Werkzeug-0.12.2-py2.6.egg/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.6/site-packages/Werkzeug-0.12.2-py2.6.egg/werkzeug/serving.py", line 168, in write
    self.send_header(key, value)
  File "/usr/lib64/python2.6/BaseHTTPServer.py", line 390, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

```

**Comment by sivashankerN** [comment]
There is a problem in DISKINODES in OpenVZ container.
Modified DISKINODES value in OpenVZ configuration file  `/etc/vz/conf/*vswap-256m*` and this file used in `/etc/vz/vz.conf` to create container with default values.
